server:
  tomcat:
    accesslog:
      enabled: true




spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  datasource:
    url: ${dbUrl}
    username: ${dbUser}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver

jwtSecret: ${jwtSecret}
